### PR TITLE
Update UNL Alert styles

### PR DESCRIPTION
**Pull request by skoolbus39**
The cream-on-orange color scheme for the alert was not color contrast compliant.

### CODE REVIEW

**Review by jsturek — APPROVED** [review]
Looks good

**Comment by jsturek** [comment]
Screen Shot 2020-09-16 at 4 15 03 PM

**Comment by jsturek** [comment]
Does it need to be updated for 5.0 and/or 5.1? Probably not necessary just a heads up.

**Comment by skoolbus39** [comment]
Possibly, but I will go ahead and merge. We can discuss and determine whether to update for 5.0 and 5.1.

**Pull request merged**
