### PR TITLE
Set default font to Gotham

### PR DESCRIPTION
**Pull request by skoolbus39**
Replace Mercury (serif) with Gotham (sans serif) as the default font for the UNL 5.2 theme.

### CODE REVIEW

**Comment by ericras** [comment]
Is this a 5.2 thing or is this happening now?

**Comment by skoolbus39** [comment]
It's for 5.2. I've updated the branch.

**Comment by jsturek** [comment]
Same issues with changes made to 5.1 directory and not 5.2.  I would finish the visit/apply/give and once merged into 5.2, start a new branch from the updated 5.2 and apply these changes again.

**Comment by skoolbus39** [comment]
Replaced by #1431

**Pull request closed without merging**
