### PR TITLE
Implement the IDM plugin

### PR DESCRIPTION
**Pull request by mfairchild365**
This does the following:

1. Implements the analytics plugin (because it initiates the idm plugin)
2. Implements the idm plugin with dropdown functionality working
3. Adds a dropdown widget plugin for possible re-use

@skoolbus39 still needs some styling love. Is that something you can do after this is merged?

### CODE REVIEW

**Comment by skoolbus39** [comment]
@mfairchild365 I can definitely add styling after this is merged.

**Comment by tlemburg** [comment]
This looks good, however, the ?service URL attr is missing (it did not redirect me back). Since we are styling this later, please make an issue with a 5.0 label in the issues since that is a task that still needs completed.

**Comment by mfairchild365** [comment]
Looks like there is a merge conflict now anyway. I will work on that.

**Comment by mfairchild365** [comment]
@tlemburg I did a bunch more refactoring and fixed the service URL issue you found.

**Comment by tlemburg** [comment]
Pulled tested looks good

**Pull request merged**
