### PR TITLE
Closes #1164 - Re-add chat for 5.0

### LINKED ISSUE #1164: Integrate UNL Chat into 5.0 theme

### PR DESCRIPTION
**Pull request by ericras**
#1164 

Bulk of the work occurred in the chat project: https://github.com/unl/VisitorChat/pull/361

This adds the chat initialization right back to where it was in 4.1.  It can possibly be moved later to a plugin of its own (?)

### CODE REVIEW

**Comment by ericras** [comment]
Needs hooked up to the new mobile nav bar still

**Comment by ericras** [comment]
I think this is ready now

9afc3b7cfaac6aaec3f943c0e4a59f1bcdee91da

**Comment by jsturek** [comment]
Currently the chat doesn't display nicely in mobile when user in one of the other mobile menu toggle open states.  i.e. when mobile nav is open the chat doesn't display.  I talked to Ryan and making the z-index high enough to display over the open states of the other mobile menu states will make chat behave as desired (except for search currently (chrome) since it's a dialog).  This will allow chat and the other mobile menu items to both be open at the same time.

**Comment by ericras** [comment]
Is there a reason the search results needs to be 100149?

**Comment by ericras** [comment]
Setting #visitorChat z-index to 999999 within the chat application

**Pull request merged**
