### PR TITLE
remove margin to last element

### PR DESCRIPTION
**Pull request by cmdprompt**
This is causing white bars to appear on our site where their shouldn't be.

### CODE REVIEW

**Comment by cmdprompt** [comment]
image

**Comment by kabel** [comment]
The margin is getting added because of your `#aspnetForm` not having `.wdn-band` or adding to your CSS overrides for `#maincontent > form, #maincontent > .main-form`. 

The goal of this CSS is to prevent content not in bands from accidentally bumping into the bottom of the page. Something that was very common for pages that haven't converted to use these new layout classes.

**Comment by cmdprompt** [comment]
Is your suggested solution to put `.wdn-band` on that form then?

**Comment by kabel** [comment]
That, or change the specificity of your styles selector (add the `#aspnetForm` prefix to the second part), or add `! important` to your `margin` property.

**Pull request closed without merging**
