### PR TITLE
Add wdn-hero content module

### PR DESCRIPTION
**Pull request by skoolbus39**

### CODE REVIEW

**Comment by skoolbus39** [comment]
This still needs to include the Picturefill polyfill for the picture element before deployment.

**Comment by mfairchild365** [comment]
Not necessary for this PR, but this could use some documentation love on the WDN site too.

**Comment by skoolbus39** [comment]
I started the documentation, but have held off until we decide on how to handle the Picturefill polyfill.

**Comment by skoolbus39** [comment]
We've decided not to implement the Picturefill polyfill for this release.

**Pull request merged**
