### PR TITLE
Add `dcf-no-webp` class to `<html>`

### PR DESCRIPTION
**Pull request by skoolbus39**

### CODE REVIEW

**Comment by jsturek** [comment]
Missing some files (maybe on purpose):
Note some of these still have `no-js` instead of `dcf-no-js`.  Maybe some just need to go away.

- [ ] affiliate.shtml
- [ ] bio.shtml
- [ ] debug.compiled.html
- [ ] debug.shtml
- [ ] document.shtml
- [ ] fixed.shtml
- [ ] plugin-build.shtml
- [ ] secure.shtml
- [ ] ux-test.shtml

**Comment by jsturek** [comment]
- [ ] Update DCF to get lazy load fix

**Comment by skoolbus39** [comment]
@jsturek, I updated the files that had already been updated to 5.x. I did, however, miss a few files. Good catch. 

_affiliate_ still needs to be updated to 5.x, but will require some additional work.

_debug.compiled.html_ is in _.gitignore_.

_bio_ and _ux-test_ can eventually be removed.

@ericras, are _document_, _fixed_ and _secure_ still needed?

**Comment by jsturek** [comment]
@skoolbus39, the remaining files can be addressed later.  You may merge these changes.

**Pull request merged**
